### ISSUE TITLE
What is license?

### ISSUE THREAD

**Issue by ducha-aiki** [facebookresearch/silk#1]
Readme says: 

> SiLK is licensed under a Attribution-NonCommercial 4.0 International License, as specified in the [LICENSE](https://github.com/facebookresearch/silk/blob/main/LICENSE) file.

However in LICENSE we have GPL-3.0:

https://github.com/facebookresearch/silk/blob/main/LICENSE

**Comment by gleize** [comment]
The license is GPL-3.0.

Thanks @ducha-aiki  for pointing out the inconsistency. This will be fixed in a subsequent update.

**Comment by ducha-aiki** [comment]
GPL-3 is sad, but thank you anyway :)
