### ISSUE TITLE
Training SuperPoint

### ISSUE THREAD

**Issue by mhwang003** [facebookresearch/silk#20]
Hi, Thanks for sharing this incredible work!

How might I train superpoint in this repo?

**Comment by gleize** [comment]
Hi @mhwang003,

There is documentation [here](https://github.com/facebookresearch/silk/tree/9d80ebd81212c75d3638bd2d77c18bc48af7f5b5/doc/models).

Training `SuperPoint` requires to first train a model called `MagicPoint`, then you need to run the training of `SuperPoint` twice. The doc should be clear enough, but don't hesitate to mention if you run into any issues.

**Comment by mhwang003** [comment]
Thank you! I will look into it.

**Comment by mhwang003** [comment]
When training superpoint in phase-1 I encountered this error. Is there something I am doing wrong? 
```
raise InstantiationException(msg) from e
          │                      └ "Error locating target 'silk.config.hardware.get_cpus', see chained exception above.\nfull_key: default.loader.defaults.workers"
          └ <class 'hydra.errors.InstantiationException'>

omegaconf.errors.InterpolationResolutionError: InstantiationException raised while resolving interpolation: Error locating target 'silk.config.hardware.get_cpus', see chained exception above.
full_key: default.loader.defaults.workers
    full_key: default.loader.defaults.workers._value_
    object_type=dict
```

**Comment by gleize** [comment]
Hi @mhwang003,

I could not reproduce the crash on my side. Everything ran smoothly.

So, in your case, it seems hydra isn't able to locate the function `silk.config.hardware.get_cpus`, but I see it [here](https://github.com/facebookresearch/silk/blob/9d80ebd81212c75d3638bd2d77c18bc48af7f5b5/lib/config/hardware.py#L15).
Did you change the code structure by any chance ? Did you follow the suggested step to setup the python environment ? Is the python environment active ?

Try running `from silk.config.hardware import get_cpus` in python to check if the function is accessible or not. If python can access it, but hydra cannot, maybe your version of hydra / omegaconf is causing the issue. Make sure you're running the same version as specified [here](https://github.com/facebookresearch/silk/blob/9d80ebd81212c75d3638bd2d77c18bc48af7f5b5/requirements.txt#LL6C1-L6C1).

**Comment by mhwang003** [comment]
thank you very much for the reply! There was a problem with my python environment.

**Comment by ssjsuueusjsh** [comment]
I would like to ask, how long does it take to train the two phases of superpoint？
