### ISSUE TITLE
Hard-coded scale factor

### ISSUE THREAD

**Issue by mertkaraoglu** [facebookresearch/silk#22]
How did you end up with the [descriptor scaling factor](https://github.com/facebookresearch/silk/blob/main/scripts/examples/common.py#L36) `1.41`. Can you elaborate on the intuition of why such a scale is practically beneficial?

**Comment by gleize** [comment]
Hi @mertkaraoglu,

`SILK_SCALE_FACTOR` is a scaling factor of the descriptors (desc <- SILK_SCALE_FACTOR * desc) done after unit normalization. A value of 1.41 (square root of 2) will essentially bring the descriptors on the hypersphere surface of radius 2. This is here for legacy reasons, and has little importance (with the exception mentioned below). You can just treat it as a constant.

Moreover, changing that value won't change the MNN matching, nor the ratio-test. BUT, it will affect the double-softmax matching, as changing `SILK_SCALE_FACTOR` is similar to changing the softmax temperature.

**Comment by mertkaraoglu** [comment]
Yes, I see; thanks for the reply.
