### ISSUE TITLE
Could you please give me a concise model code

### ISSUE THREAD

**Issue by LANSHANGH** [facebookresearch/silk#23]
I want to try out how the model looks in the various data sets，And try to make some modifications on the model to see if we can get better results

**Comment by gleize** [comment]
Hi @LANSHANGH,

* Datasets can be added in `etc/datasets` (c.f. existing datasets so see how to configure yours). Once ready, you can point to your newly created dataset [here](https://github.com/facebookresearch/silk/blob/b601cbc5458c0e5504e75bff4e138532c1ce683a/etc/mode/train-silk.yaml#LL7C41-L7C41).
* The backbones are configured in `etc/backbones` and selected [here](https://github.com/facebookresearch/silk/blob/b601cbc5458c0e5504e75bff4e138532c1ce683a/etc/models/silk-vgg.yaml). You can add your own or modify existing ones.

As for the "concise model code", we do not have a simpler version of the code right now. This might change in the future.
