### ISSUE TITLE
Setup Instructions

### ISSUE THREAD

**Issue by kkaytekin** [facebookresearch/silk#31]
Hi there,
thanks for sharing your code. Following the setup instructions, I face the following error when I type `make dev_install`:
 ```
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error: supposed package directory 'silk' exists, but is not a directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
make: *** [Makefile:11: dev_install] Error 1
```
In `setup.py`, when I make the following change, no error is thrown:
```
from setuptools import find_packages
setup(
    name="SiLK Keypoint Library",
    version="1.0",
    description="[FAIR] SiLK - Simple Learned Keypoints",
    author="Pierre Gleize, Weiyao Wang, Matt Feiszli",
    author_email="gleize@meta.com",
    url="https://github.com/facebookresearch/silk",
    packages=find_packages(["silk"]), # Change: Use find_packages() here
    install_requires=load_requirements("requirements.txt"),
)
```
Package installation seems to be successful, and `miniconda3/envs/silk/lib/python3.8/site-packages/SiLK-Keypoint-Library.egg-link` is created. But I cannot import it in python (`ModuleNotFoundError: No module named 'silk'`).
What might be causing this problem? I am using archlinux.
Thanks :)

**Comment by gleize** [comment]
Hi @kkaytekin,

This line `error: supposed package directory 'silk' exists, but is not a directory` suggests there might be an issue with the symlink on archlinux.
What you can try :
1. Revert the change in `setup.py`.
2. Remove the symlink : `rm silk`.
3. Duplicate the `lib` directory to `silk` : `cp -r lib silk`
4. Run the setup again.

This is ugly but it should work.

**Comment by kkaytekin** [comment]
Thank you! True, the problem was with symlink. Removing the symlink and creating it manually solved the problem. i.e.
1. Remove the symlink from the repo: `rm silk`.
2. Create the symlink yourself: `ln -s ./lib silk`
This way no additional disk space is used. Thanks for the help!

**Comment by 52THANOS** [comment]
> Thank you! True, the problem was with symlink. Removing the symlink and creating it manually solved the problem. i.e.
> 
> 1. Remove the symlink from the repo: `rm silk`.
> 2. Create the symlink yourself: `ln -s ./lib silk`
>    This way no additional disk space is used. Thanks for the help!

New-Item -ItemType SymbolicLink -Path "silk" -Value "./lib" -Force
this is windows command to Create the symlink
