### ISSUE TITLE
How might I train SiLK on gray scale images?

### ISSUE THREAD

**Issue by mhwang003** [facebookresearch/silk#34]
Hi, I have a question regarding the training code of SiLK.

I was trying to load gray scale images (image dims: torch.Size([260, 346])) and I got an error as shown below.

```
File "/silk/silk/transforms/cv/image.py", line 52, in __call__
    raise RuntimeError("invalid tensor shape, 3 or 4 dimensions are expected")
```

It seems that the class HWCToCHW which is declared in image.py was called in silk/transforms/abstract.py but I do not quite understand the workings of the image loading process. Is there a work around for gray scale images? 
Any advice will be very helpful. 
Thank you.

**Comment by gleize** [comment]
Hi @mhwang003,

The image augmentation pipeline requires RGB inputs. So if you want to run on grayscale images without changing the SiLK codebase, you can stack the grayscale images, i.e. duplicate it to create an image with 3 channels.
After you do that, make sure that the images provided by your dataset are numpy array with `dtype=uint8` and `shape=(H,W,3)`.
