### ISSUE TITLE
Problems with inference

### ISSUE THREAD

**Issue by haksorus** [facebookresearch/silk#35]
Hello, thanks for the great work!

I'm having some problems with SILK default inference scheme. In my case, I just tried to match two satellite images (**HxW = 640x640** both) using **silk-inference.py** with standard parameters:
```
SILK_NMS = 0  # NMS radius, 0 = disabled
SILK_BORDER = 0  # remove detection on border, 0 = disabled
SILK_THRESHOLD = 1.0  # keypoint score thresholding, if # of keypoints is less than provided top-k, then will add keypoints to reach top-k value, 1.0 = disabled
SILK_TOP_K = 10000  # minimum number of best keypoints to output, could be higher if threshold specified above has low value

# ...etc.
```
For "sparse_positions" and "sparse_descriptors", I get an empty vectors at the output. 

![telegram-cloud-photo-size-2-5436093953284886288-x](https://github.com/facebookresearch/silk/assets/69139386/05f63395-a048-47fc-944f-8d591913bbc2)

But when I enable option **SILK_THRESHOLD** (for example, changing value to **0.99**), then the values of the vectors appear. 

![telegram-cloud-photo-size-2-5436093953284886315-x](https://github.com/facebookresearch/silk/assets/69139386/cbd93df4-c649-4df6-afa6-e9cde883c7ed)

Unfortunately, the number of vector values in this case is always large and option **SILK_TOP_K** with any thresholding does not help (**descriptor shape  == torch.Size([383110, 128])**). Of course in this case I get a  **CUDA out of memory** error.

My question is, what exactly am I doing wrong?

P.S. I have tried both **pvgg-4.ckpt** and **coco-rgb-aug.ckpt** available weights.

**Comment by gleize** [comment]
Hi @haksorus,

Your image's value range seems to be $[0, 255]$ while it should be $[0, 1]$. This could cause saturation of the detection scores and thus cause the problem you mention.
Have you tried using our image [loader](https://github.com/facebookresearch/silk/blob/0a7da0168ba4fe2f4e49ebff0980ebcff0d2a1b3/scripts/examples/silk-inference.py#L21) ?
If yes, are your inputs RGB or Greyscale ?

**Comment by haksorus** [comment]
Adding image normalization to **[0,1]** solved my problem

Thank you very much!
