### ISSUE TITLE
There is a problem with the python environment.

### ISSUE THREAD

**Issue by Martin0Li** [facebookresearch/silk#5]
1.jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
I fix it with [https://github.com/google/jax/issues/15268#issuecomment-1488847725](url)
`pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

2.There is a problem about pytorch_lightning when training with ddp. It gets stuck after epoch one.
I try to fix it with [https://github.com/Lightning-AI/lightning/issues/17389#issuecomment-1511908111](url).
And I got this.
lightning.fabric.utilities.exceptions.MisconfigurationException: We could not infer the batch_size from the batch. Either simplify its structure or provide the batch_size as `self.log(..., batch_size=batch_size)`

**Comment by Martin0Li** [comment]
There is a problem about pytorch_lightning when training with ddp. It gets stuck after epoch one.
I fix it with https://github.com/Lightning-AI/lightning/issues/15545#issuecomment-1323421123
`pip install lightning==1.8.3`

**Comment by gleize** [comment]
Hi @Martin0Li ,

Thanks for pointing out those issues.

I found those errors were caused by more recent versions of jax and hydra.
I've pushed a [fix](https://github.com/facebookresearch/silk/commit/70ea0547771661ba26fc2a052592b9e565618973) that freezes the versions instead of allowing more recent ones.

**Comment by Martin0Li** [comment]
Thank you very much for your response. Based on the updates you provided, I was able to successfully resolve my python environment issues.
