### ISSUE TITLE
Ratio-Test distance question

### ISSUE THREAD

**Issue by AliYoussef97** [facebookresearch/silk#55]
Hello!

I had a question regarding ratio-testmatching. From the silk-inference.py script, the model returns [sparse_positions and sparse_descriptors](https://github.com/facebookresearch/silk/blob/0e5a823a5e635b171ab908353dcb6e0a573fd58d/scripts/examples/silk-inference.py#L25C1-L26C1), which from the model's code, sprase descriptors are computed using the raw_descriptors [here](https://github.com/facebookresearch/silk/blob/0e5a823a5e635b171ab908353dcb6e0a573fd58d/lib/backbones/silk/silk.py#L201C1-L210C9) which are normalised during the [process](https://github.com/facebookresearch/silk/blob/0e5a823a5e635b171ab908353dcb6e0a573fd58d/lib/backbones/silk/silk.py#L263C1-L268C1). However, I am not compeltely sure why during the ratio-test distance computation, the descriptors are normalised [once more](https://github.com/facebookresearch/silk/blob/0e5a823a5e635b171ab908353dcb6e0a573fd58d/lib/matching/mnn.py#L19C9-L28C10)?

Thank you!

**Comment by gleize** [comment]
Hi @AliYoussef97,

Sorry for the late reply. It's entirely possible I might run the normalization twice. It won't change the results but will indeed add unnecessary computation. If your descriptors are already normalized, you can set the `dist_type` argument to "dot" in the [compute_dist](https://github.com/facebookresearch/silk/blob/0e5a823a5e635b171ab908353dcb6e0a573fd58d/lib/matching/mnn.py#L13C5-L13C17) function. It will return the same results without re-normalizing twice.

**Comment by AliYoussef97** [comment]
@gleize Understood! 

Thank you very much!
