### ISSUE TITLE
Training Configuration File for coco-rgb-aug Weights

### ISSUE THREAD

**Issue by wangerniuniu** [facebookresearch/silk#62]
Could you please point me to the correct training configuration file for the` coco-rgb-aug `model? If it's available in a repository, a link would be greatly appreciated.

**Comment by AliYoussef97** [comment]
Hello @wangerniuniu 

Based on the FAQ [here](https://github.com/facebookresearch/silk/blob/main/doc/usage/faq.md#:~:text=Checkpoint.%20We%20provide%20two%20checkpoints%20for%20our%20VGG%2D4%20backbone%20%3A%20pvgg%2D4.ckpt%20and%20coco%2Drgb%2Daug.ckpt%20(trained%20with%20different%20photometric%20augmentations).%20Try%20both%20and%20see%20which%20one%20performs%20best.), `coco-rgb-aug` and `pvgg-4` are the same model but different photometric augmentation during training.

I believe the default training in this repository leads to the `coco-rgb-aug` model, however the authors can correct me of course.

If we follow the configration tree, we start at the [`train-silk.yaml`](https://github.com/facebookresearch/silk/blob/bd605bf4180c05a42dae0d807412b40ce0dbcc21/etc/mode/train-silk.yaml) file, where the 3rd line has `/models@model: silk-vgg` as the default. If we go to the [`silk-vgg.yaml`](https://github.com/facebookresearch/silk/blob/main/etc/models/silk-vgg.yaml) we can see the training regime is `silk-rand-homo` with a backbone of `silk-pvgg-4`. We then go [`silk-rand-homo.yaml`](https://github.com/facebookresearch/silk/blob/main/etc/models/silk-rand-homo.yaml), which on the 2nd line has `silk-default` configuration as the default configuartion. Finally, going to [`silk-default.yaml`](https://github.com/facebookresearch/silk/blob/bd605bf4180c05a42dae0d807412b40ce0dbcc21/etc/models/silk-default.yaml), we can see the photometric augmentation [here](https://github.com/facebookresearch/silk/blob/bd605bf4180c05a42dae0d807412b40ce0dbcc21/etc/models/silk-default.yaml#L19-L44), line 20 states that this is the photometric used for `IMC (4.3) and ScanNet (4.4.1)` which are table 4. and table 5. in the SiLk paper. The ReadMe file states[`here`](https://github.com/facebookresearch/silk#:~:text=(checkpoint%20pvgg%2D4.ckpt%20for%20tab%202%2C3%2C6%20and%20coco%2Drgb%2Daug%20for%20tab%204%2C5).), that the `coco-rgb-aug` model was used to produce table 4. and 5. results, that is why I believe the default training configuration results in the `coco-rgb-aug` model.

Of course, the authors can correct me if I pointed you in the wrong direction, hope this helps!

**Comment by gleize** [comment]
Hi @wangerniuniu,

Thanks @AliYoussef97 for the explanation.
Yes, that's exactly right. The default setup is for training the `coco-rgb-aug` version, which only changes the photo-metric augmentation.
